name: 'Docker Publish'

on:
    workflow_call:
        inputs:
            newTag:
                description: "The new version tag for the docker image"
                required: true
                type: string
            imageName:
                description: "The name of the docker image"
                required: true
                type: string
            dockerfilePath:
                description: "The path to the Dockerfile"
                required: false
                type: string
                default: "./Dockerfile"
        secrets:
            DOCKER_USERNAME:
                required: true
            DOCKER_PASSWORD:
                required: true
            GH_PAT_TOKEN:
                required: true

jobs:
    publish:
        name: 'Build and Push Docker Image'
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -   name: 'Checkout'
                uses: actions/checkout@v4
                with:
                    token: ${{ secrets.GH_PAT_TOKEN }}

            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                  images: |
                    ${{ inputs.imageName }}
                  tags: |
                    type=semver,pattern=v{{version}},value=${{ inputs.newTag }}
                    type=semver,pattern=v{{major}}.{{minor}},value=${{ inputs.newTag }}
                    type=semver,pattern=v{{major}},value=${{ inputs.newTag }}
                    type=sha

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3
                
            -   name: 'Set up Docker Buildx'
                uses: docker/setup-buildx-action@v3

            -   name: 'Log in to Docker Hub'
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: 'Build and push Docker image'
                uses: docker/build-push-action@v5
                with:
                    context: .
                    file: ${{ inputs.dockerfilePath }}
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    platforms: linux/amd64,linux/arm64
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
